// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addHashTag': string;
  'addNote': string;
  'addNoteTag': string;
  'description': string;
  'descriptionTools': string;
  'lore': string;
  'officialDescription': string;
  'wishListNotes': string;
}
export const cssExports: CssExports;
export default cssExports;
