// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ammo': string;
  'ammoIcon': string;
  'arcIcon': string;
  'element': string;
  'extraStuff': string;
  'heavyAmmo': string;
  'powerElement': string;
  'powerInfo': string;
  'primaryAmmo': string;
  'primaryStatName': string;
  'requiredLevel': string;
  'solarIcon': string;
  'specialAmmo': string;
  'subSection': string;
  'voidIcon': string;
}
declare var cssExports: CssExports;
export = cssExports;
