// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemHeader': string;
  'itemTitle': string;
  'masterwork': string;
  'subTitle': string;
  'tierLock': string;
  'titleContainer': string;
}
declare const cssExports: CssExports;
export = cssExports;
